/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerProcesarReclamo;
import model.UsuarioLogueado;



/**
 *
 * @author JUANA
 */
public class JFramePrincipal extends javax.swing.JFrame {
    GestorPanel gestorDePaneles;
    PanelEmpleadoSupervisor unPanelEmpleadoSupervisor;
    PanelEmpleadoExperto  unPanelEmpleadoExperto;
    ControllerProcesarReclamo controlador;
    
    int privilegio;
    public JFramePrincipal() {
        initComponents();
           
       //obtener el privilegio del usuario
       privilegio = UsuarioLogueado.getInstance().getUnUsuario().getUnTipoUsuario().getPrivilegio();
       //comprobar si el privilegio esta en este rango.
            if(privilegio!=0&&privilegio<=6){
              //si el privilegio es igual a 1 se hace lo siguiente.
                     if(privilegio==1){
                    //se instancia el controlador y se crea un Gestor de paneles que contendra todos los paneles.
                     controlador = new ControllerProcesarReclamo();
                     gestorDePaneles = new GestorPanel(controlador);
                     gestorDePaneles.setBounds(0, 0, 1500, 750); 
                     gestorDePaneles.setVisible(true);   
                       this.add(gestorDePaneles);  
                     }
                     //se instancia el controlador y se crea un panel empleado experto.
                     if(privilegio==4){
                     controlador = new ControllerProcesarReclamo();
                     unPanelEmpleadoExperto = new PanelEmpleadoExperto(controlador);
                     unPanelEmpleadoExperto.setBounds(0, 0, 1500, 750); 
                     unPanelEmpleadoExperto.setVisible(true);   
                       this.add(unPanelEmpleadoExperto);  
                     }
                     
                     if(privilegio==5){
                     controlador = new ControllerProcesarReclamo();
                     unPanelEmpleadoSupervisor = new PanelEmpleadoSupervisor(controlador);
                     unPanelEmpleadoSupervisor.setBounds(0, 0, 1500, 750);
                     unPanelEmpleadoSupervisor.setVisible(true);
                     this.add(unPanelEmpleadoSupervisor);
                     }
            }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
